# Generated by Django 5.1.3 on 2024-11-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bank_loan',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=22)),
                ('bank_id', models.IntegerField()),
                ('loan_amount', models.IntegerField()),
                ('loan_id', models.IntegerField()),
            ],
        ),
    ]
